" makes a lot of things possible
set nocompatible

" good defaults
set number
set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4
set backspace=indent,eol,start
set autoindent
set smartindent
set cindent

" No littering
set noswapfile
set nobackup
set nowritebackup
set viminfo=""
set noundofile

" A good color scheme

" Override default keys because I am horrible
map Q <Nop>
map q <Nop>
noremap x "_x

" I forget what this does
let &t_ut=''

" Tabs, splits
set splitright
" Status Line {
        set laststatus=2                             " always show statusbar
        set statusline="  "
        set statusline+=%3n\                     " buffer number
        set statusline+=%10f\                          " filename
        set statusline+=%h%m%r%w                     " status flags
        set statusline+=\[%{strlen(&ft)?&ft:'none'}] " file type
        set statusline+=%=                           " right align remainder
        set statusline+=0x%-8B                       " character value
        set statusline+=%-14(%l,%c%V%)               " line, character
        set statusline+=%<%P                         " file position
"}

" GUI only
if has("gui_running")
	:set guifont=Cascadia_Mono:h16:cANSI:qDRAFT
endif

" colorscheme
" This is a modified version of the full source code of Vim's :colorscheme ron
set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
" let g:colors_name = "ron"
hi Normal		guifg=cyan	guibg=black
hi NonText		guifg=brown
hi comment		guifg=green
hi constant		guifg=cyan	gui=bold
hi identifier	guifg=cyan	gui=NONE
hi statement	guifg=lightblue	gui=NONE
hi preproc		guifg=Pink2
hi type			guifg=seagreen	gui=bold
hi special		guifg=yellow
hi ErrorMsg		guifg=Black	guibg=Red
hi WarningMsg	guifg=Black	guibg=Green
hi Error		guibg=Red
hi Todo			guifg=Black	guibg=orange
hi Cursor		guibg=#60a060 guifg=#00ff00
hi Search		guibg=lightslateblue
hi IncSearch	gui=NONE guibg=steelblue
hi LineNr		ctermfg=lightcyan
hi title		guifg=darkgrey
hi label		guifg=gold2
hi operator		guifg=orange
hi clear Visual
hi Visual		term=reverse cterm=reverse gui=reverse
hi DiffChange   guibg=darkgreen
hi DiffText		guibg=olivedrab
hi DiffAdd		guibg=slateblue
hi DiffDelete   guibg=coral
hi Folded		guibg=gray30
hi FoldColumn	guibg=gray30 guifg=white
hi cIf0			guifg=gray
hi StatusLine ctermbg=lightcyan
hi StatusLine ctermfg=black

" An amazing command
com! Typehi echo {l,c,n ->
        \   'hi<'    . synIDattr(synID(l, c, 1), n)             . '> '
        \  .'trans<' . synIDattr(synID(l, c, 0), n)             . '> '
        \  .'lo<'    . synIDattr(synIDtrans(synID(l, c, 1)), n) . '> '
        \ }(line("."), col("."), "name")

syntax on
