#!/bin/bash
b="";
g="";
if [ $# -eq 0 ]
then
	b="1.0";
	g="1:1:1";
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
	echo -e "Usage:\nlight [ 'red' or '' ] [ brightness level in range 0.0 - 1.0 (default 1.0) ]"
	exit 0
elif [ "$1" = "red" ] && [ $# -eq 1 ]
then
	b=".5";
	g="1:.7:.5";
elif [ "$1" = "red" ] && [ $# -eq 2 ]
then
	b=$2;
	g="1:.7:.5";
else
	b=$1;
	g="1:1:1";
fi
for disp in $(xrandr | grep '[^(dis)]connected' | cut -d ' ' -f 1); do xrandr --output "$disp" --gamma "$g" --brightness "$b"; done
